%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
# dataset_dir: /home/ricky/ORBSLAM2/rgbd_dataset_freiburg1_desk

dataset_dir: /home/ricky/文档/SLAM_PRJ/slam_default2/rgbd_dataset_freiburg1_xyz
pointSizeCur: 3.15
pointSizeHis: 2.75
waitTime: 1
# 0 no 1 yes
dense: 0  